/*
 * HAL_STM32F411_RCC.c
 *
 *  Created on: Nov 12, 2024
 *      Author: MinhTan
 */
#include <HAL_STM32F411_RCC.h>

void HAL_RCC_SetSystemClockByPLL(void)
{

#if HSI_PLL_CLOCK
SET_BIT(RCC->CR,RCC_CR_HSION); //16Mhz
while(!(RCC->CR & (SET_BIT(RCC->CR,RCC_CR_HSIRDY))));
RCC->PLLCFGR =(PLL_M << RCC_CFGR_PLLM);//SET_BIT(RCC_CFGR_PLLM,PLL_M);
RCC->PLLCFGR =(PLL_N << RCC_CFGR_PLLN);//SET_BIT(RCC_CFGR_PLLN,PLL_N);
RCC->PLLCFGR =(PLL_P << RCC_CFGR_PLLP);//SET_BIT(RCC_CFGR_PLLP,PLL_P);
SET_BIT(RCC->PLLCFGR,RCC_PLLCFGR_SRC_HSI);

SET_BIT(RCC->CFGR,HPRE_CLOCK_DIV_1);
SET_BIT(RCC->CFGR,PPRE1_CLOCK_DIV2);
SET_BIT(RCC->CFGR,PPRE2_CLOCK_DIV1);

SET_BIT(RCC->CFGR,RCC_PLL_SW);
while(!(RCC->CFGR & RCC_PLL_SWS));
#else // HSE_PLL_CLOCK
SET_BIT(RCC->CR, RCC_CR_HSEON); //8MHZ
while(!(RCC->CR & (SET_BIT(RCC->CR,RCC_CR_HSERDY))));
RCC->PLLCFGR =(PLL_M << RCC_CFGR_PLLM);//SET_BIT(RCC_CFGR_PLLM,PLL_M);
RCC->PLLCFGR =(PLL_N << RCC_CFGR_PLLN);//SET_BIT(RCC_CFGR_PLLN,PLL_N);
RCC->PLLCFGR =(PLL_P << RCC_CFGR_PLLP);//SET_BIT(RCC_CFGR_PLLP,PLL_P);
SET_BIT(RCC->PLLCFGR,RCC_PLLCFGR_SRC_HSE);

SET_BIT(RCC->CFGR,HPRE_CLOCK_DIV_1);
SET_BIT(RCC->CFGR,PPRE1_CLOCK_DIV2);
SET_BIT(RCC->CFGR,PPRE2_CLOCK_DIV1);
SET_BIT(RCC->CFGR,RCC_PLL_SW);
while(!(RCC->CFGR & RCC_PLL_SWS));
#endif
SET_BIT(RCC->CR, RCC_CR_PLL);
while(!(RCC->CR &(SET_BIT(RCC->CR,RCC_CR_PLLRDY))));
}

void HAL_RCC_SetSystemClockTo16Mhz(void)
{
	SET_BIT(RCC->CR,RCC_CR_HSION);
    while(!(RCC->CR & (SET_BIT(RCC->CR,RCC_CR_HSIRDY))));
	RCC->CFGR |= HPRE_CLOCK_DIV_1;
	RCC->CFGR |= PPRE1_CLOCK_DIV1 <<10;
	RCC->CFGR |= PPRE2_CLOCK_DIV1 <<13;
	SET_BIT(RCC->CFGR,RCC_HSI_SW);
	while(!(RCC->CFGR & RCC_HSI_SWS));
	RCC->CR &=~ RCC_CR_HSEON;
}
void HAL_RCC_SetSystemClockTo8Mhz(void)
{
		SET_BIT(RCC->CR,RCC_CR_HSEON);
		while((RCC->CR & (SET_BIT(RCC->CR,RCC_CR_HSERDY))));
		RCC->CFGR |= HPRE_CLOCK_DIV_1;
		RCC->CFGR |= PPRE1_CLOCK_DIV1 <<10;
		RCC->CFGR |= PPRE2_CLOCK_DIV1 <<13;
		CLR_BIT(RCC->CFGR,RCC_HSE_SW);
		while(!(RCC->CFGR & RCC_HSE_SWS));
		RCC->CR &=~ RCC_CR_HSION;
}

void HAL_RCC_SetSystemClock()
{
#if HSI_CLOCK_ENABLE
	HAL_RCC_SetSystemClockTo16Mhz();
#elif HSE_CLOCK_ENABLE
	HAL_RCC_SetSystemClockTo8Mhz();
#else
	HAL_RCC_SetSystemClockByPLL();
#endif
}
void HAL_GPIOA_ENABLE_CLOCK()
{
	RCC->AHB1ENR |= RCC_GPIOAENR;
}

void HAL_GPIOB_ENABLE_CLOCK()
{
	RCC->AHB1ENR |= RCC_GPIOBENR;
}
void HAL_GPIOC_ENABLE_CLOCK()
{
	RCC->AHB1ENR |= RCC_GPIOCENR;
}
void HAL_GPIOD_ENABLE_CLOCK()
{
	RCC->AHB1ENR |= RCC_GPIODENR;
}
void HAL_GPIOE_ENABLE_CLOCK()
{
	RCC->AHB1ENR |= RCC_GPIOEENR;
}
void HAL_GPIOH_ENABLE_CLOCK()
{
	RCC->AHB1ENR |= RCC_GPIOHENR;
}

////////
void HAL_TIM1_ENNABLE_CLOCK()
{
	RCC->APB2ENR |= RCC_TIM1ENR;
}

void HAL_TIM2_ENNABLE_CLOCK()
{
	RCC->APB1ENR |= RCC_TIM2ENR;
}
void HAL_TIM3_ENNABLE_CLOCK()
{
	RCC->APB1ENR |= RCC_TIM3ENR;
}
void HAL_TIM4_ENNABLE_CLOCK()
{
	RCC->APB1ENR |= RCC_TIM4ENR;
}

void HAL_TIM5_ENNABLE_CLOCK()
{
	RCC->APB1ENR |= RCC_TIM5ENR;
}

void HAL_TIM9_ENNABLE_CLOCK()
{
	RCC->APB2ENR |= RCC_TIM9ENR;
}
void HAL_TIM10_ENNABLE_CLOCK()
{
	RCC->APB2ENR |= RCC_TIM10ENR;
}
void HAL_TIM11_ENNABLE_CLOCK()
{
	RCC->APB2ENR |= RCC_TIM11ENR;
}
